### ISSUE TITLE
SYNTROPY_NAMESPACE does work properly when multiple namespaces are set

### ISSUE THREAD

**Issue by tomasliumparas** [SyntropyNet/syntropy-agent#11]
Hey,

## Summary
When setting `SYNTROPY_NAMESPACE` to multiple namespaces separated with comma, as mentioned here:
https://docs.syntropystack.com/docs/syntropy-agent-variables#syntropy-namespace

Syntropy agent sends empty list of services.

## How to reproduce
* Set multiple namespaces on `SYNTROPY_NAMESPACE: "prometheus-legacy,budget"`
* Restart syntropy-agent
* Syntropy-agent will send empty service list
```
[DBG] 2022/07/22 14:27:21 Kubernetes.  Sending:  {"id":"-","type":"KUBERNETES_SERVICE_INFO","executed_at":"2022-07-22T14:27:21Z","data":[]}
```
* Having only single namespace set `SYNTROPY_NAMESPACE: "prometheus-legacy"` , works as expected:
```
DBG] 2022/07/22 14:31:59 Kubernetes.  Sending:  {"id":"-","type":"KUBERNETES_SERVICE_INFO","executed_at":"2022-07-22T14:31:59Z","data":[{"agent_service_name":"exporter-blackbox","agent_service_subnets":"10.233.12.216","agent_service_ports":{"tcp":[9115],"udp":[]}},{"agent_service_name":"exporter-consul","agent_service_subnets":"10.233.51.210","agent_service_ports":{"tcp":[9107],"udp":[]}},{"agent_service_name":"exporter-goflow","agent_service_subnets":"10.233.15.184","agent_service_ports":{"tcp":[8080],"udp":[]}},{"agent_service_name":"exporter-goflow-lb","agent_service_subnets":"10.233.21.111","agent_service_ports":{"tcp":[],"udp":[2055]}},{"agent_service_name":"exporter-snmp","agent_service_subnets":"10.233.3.73","agent_service_ports":{"tcp":[9116],"udp":[]}},{"agent_service_name":"exporter-transmission","agent_service_subnets":"10.233.21.5","agent_service_ports":{"tcp":[19091],"udp":[]}},{"agent_service_name":"prometheus","agent_service_subnets":"10.233.44.166","agent_service_ports":{"tcp":[9090],"udp":[]}},{"agent_service_name":"sensu-ui","agent_service_subnets":"10.233.32.76","agent_service_ports":{"tcp":[3000],"udp":[]}}]}
```

## Environment details
Kubernetes 1.21 on-premises, running on RHEL 8.4

Service list in prometheus legacy namepace:
```
NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
exporter-blackbox       ClusterIP      10.233.12.216   <none>        9115/TCP         334d
exporter-consul         ClusterIP      10.233.51.210   <none>        9107/TCP         334d
exporter-goflow         ClusterIP      10.233.15.184   <none>        8080/TCP         8d
exporter-goflow-lb      LoadBalancer   10.233.21.111   10.67.0.51    2055:30740/UDP   8d
exporter-snmp           ClusterIP      10.233.3.73     <none>        9116/TCP         334d
exporter-transmission   ClusterIP      10.233.21.5     <none>        19091/TCP        334d
prometheus              ClusterIP      10.233.44.166   <none>        9090/TCP         334d
sensu-ui                ClusterIP      10.233.32.76    <none>        3000/TCP         334d
```
Service list in budget namespace:
```
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
budget-api        ClusterIP   10.233.25.66    <none>        8080/TCP   179d
budget-frontend   ClusterIP   10.233.5.62     <none>        80/TCP     178d
postgres-any      ClusterIP   10.233.17.7     <none>        5432/TCP   41d
postgres-r        ClusterIP   10.233.16.50    <none>        5432/TCP   41d
postgres-ro       ClusterIP   10.233.62.51    <none>        5432/TCP   41d
postgres-rw       ClusterIP   10.233.63.186   <none>        5432/TCP   41d
```

## Syntropy agent configuration
```
  SYNTROPY_LOG_LEVEL: debug
  SYNTROPY_AGENT_TOKEN: xxxxx
  SYNTROPY_AGENT_NAME: hcloud-k8s
  SYNTROPY_NETWORK_API: kubernetes
  SYNTROPY_NAMESPACE: "prometheus-legacy,budget,hc"
  SYNTROPY_SERVICES_STATUS: "true"
```

Deployment config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
  labels:
    app: syntropy-agent
    app.kubernetes.io/instance: syntropy
  name: syntropy-agent
  namespace: syntropy
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: syntropy-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: c1fc8631506afb8017b58a6a5cd736e67e2578fcca8723793127c05e3ee0c0f6
        checksum/rbac: 941e6c7c1bbaf691f29845a1eb0ffa81a55d7fa185fa66e920371386df4c0db8
        checksum/secret: 09ec5590f822e819bc3ef30bddd32d1836a62ca359bcc4b830be3b3066741089
      creationTimestamp: null
      labels:
        app: syntropy-agent
        app.kubernetes.io/instance: syntropy-agent
        app.kubernetes.io/name: syntropy-agent
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Vilnius
        envFrom:
        - secretRef:
            name: syntropy-env
        image: syntropynet/agent:stable
        imagePullPolicy: IfNotPresent
        name: agent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: syntropy-agent-config
        name: config
```

RBAC ocnfig:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syntropy-agent
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syntropy-agent
  namespace: syntropy
subjects:
- kind: ServiceAccount
  name: default 
  namespace: syntropy
roleRef:
  kind: ClusterRole 
  name: syntropy-agent
  apiGroup: rbac.authorization.k8s.io
```

## Logs
Syntropy-agent
```
[INF] 2022/07/22 14:27:15 Saas Controller.  Connecting...
[INF] 2022/07/22 14:27:15 PublicIP.  Public IP (STUN): <redacted>
[INF] 2022/07/22 14:27:16 Wireguard.  Using Wireguard implementation in-kernel
[INF] 2022/07/22 14:27:16 Syntropy Stack Agent.  /usr/bin/syntropy_agent 0.5.1 started.
[INF] 2022/07/22 14:27:16 Syntropy Stack Agent.  Using controller type:  SaaS (cloud)
[INF] 2022/07/22 14:27:16 Syntropy Stack Agent.  Local time: 2022-07-22T14:27:16Z
[WRN] 2022/07/22 14:27:16 Syntropy Stack Agent.  Kernel version is: 4.18.0-348.20.1.el8_5.x86_64
[WRN] 2022/07/22 14:27:16 Syntropy Stack Agent.  Some features may be not fully supported.
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Starting Agent messages handler
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Starting KUBERNETES_SERVICE_INFO service.
[INF] 2022/07/22 14:27:16 Kubernetes.  using in cluster config
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Starting AUTO_PING service.
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Starting PEER_WATCHER service.
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Starting IFACEMON service.
[DBG] 2022/07/22 14:27:16 SyntropyAgent.  Received:  {"id":"0aWvcztRk4gR9oXT","type":"GET_INFO","data":{}}
[DBG] 2022/07/22 14:27:16 GetInfo.  Sending:  {"id":"0aWvcztRk4gR9oXT","type":"GET_INFO","data":{"service_status":true,"agent_tags":[],"external_ip":"<redacted>","network_info":[],"container_info":[]}}
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Command 'GET_INFO' completed.
<redacted>
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Command 'AUTO_PING' completed.
<redacted>
[INF] 2022/07/22 14:27:16 Wireguard.  create interface SYNTROPY_PUBLIC
[INF] 2022/07/22 14:27:16 Wireguard.  create interface SYNTROPY_SDN1
[INF] 2022/07/22 14:27:16 Wireguard.  create interface SYNTROPY_SDN2
[INF] 2022/07/22 14:27:16 Wireguard.  create interface SYNTROPY_SDN3
[DBG] 2022/07/22 14:27:16 Config_Info.  Sending:  <redacted>
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Command 'CONFIG_INFO' completed.
[DBG] 2022/07/22 14:27:16 SyntropyAgent.  Received:  {"id":"AEMpKkxl4JA5O8sO","type":"SET_SETTINGS","data":{"rerouting_threshold":{"latency_diff":10,"latency_ratio":1.1}}}
[INF] 2022/07/22 14:27:16 SyntropyAgent.  Command 'SET_SETTINGS' completed.
[DBG] 2022/07/22 14:27:21 Kubernetes.  Sending:  {"id":"-","type":"KUBERNETES_SERVICE_INFO","executed_at":"2022-07-22T14:27:21Z","data":[]}
```
